cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/Users/vincentltz/Documents/github/ns-3-dev-git/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/Users/vincentltz/Documents/github/ns-3-dev-git/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 4421571728: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'test.cpp.1.o\', \'-o\', \'/Users/vincentltz/Documents/github/ns-3-dev-git/build/.conf_check_5ef57bc0d8aa3565949b6ce1186fd4a7/testbuild/testprog\', \'-lrt\']\n'
